export const t1Player = [
  { player: "zeus", name: "Never Daps" },
  { player: "oner", name: "아 니 맞나" },
  { player: "faker", name: "hide on bush" },
  { player: "gumayusi", name: "T1 Gumayusi" },
  { player: "keria", name: "역천괴" },
];

export const t1PlayerChamp = [
  {
    name: "hide on bush",
    champs: [
      {
        name: "Ahri",
        cs: 206.2,
        csPerMin: 8.2,
        kdaRatio: 3.88,
        kda: "5.8 / 3.3 /7.2",
        winRate: 58,
        game: 66,
      },
      {
        name: "Ryze",
        cs: 214,
        csPerMin: 8.9,
        kdaRatio: 2.94,
        kda: "4.4 / 3.6 / 6.2",
        winRate: 50,
        game: 54,
      },
      {
        name: "Vex",
        cs: 198.1,
        csPerMin: 8,
        kdaRatio: 3.4,
        kda: "5.9 / 3.7 / 6.5",
        winRate: 53,
        game: 53,
      },
      {
        name: "Lee Sin",
        cs: 141,
        csPerMin: 5.7,
        kdaRatio: 4.01,
        kda: "7.4 / 3.9 / 8.1",
        winRate: 53,
        game: 51,
      },
      {
        name: "Zoe",
        cs: 195.1,
        csPerMin: 7.8,
        kdaRatio: 3.15,
        kda: "5.0 / 3.6 / 6.3",
        winRate: 48,
        game: 50,
      },
      {
        name: "LeBlanc",
        cs: 189.5,
        csPerMin: 7.6,
        kdaRatio: 4.01,
        kda: "5.9 / 2.9 / 5.6",
        winRate: 54,
        game: 48,
      },
      {
        name: "Viktor",
        cs: 235.5,
        csPerMin: 8.7,
        kdaRatio: 2.65,
        kda: "4.6 / 3.9 / 5.8",
        winRate: 56,
        game: 43,
      },
    ],
  },
  {
    name: "Never Daps",
    champs: [
      {
        name: "Jayce",
        cs: 200.5,
        csPerMin: 7.8,
        kdaRatio: 1.65,
        kda: "6.2 / 7.0 / 5.4",
        winRate: 56,
        game: 75,
      },
      {
        name: "GangPlank",
        cs: 189.2,
        csPerMin: 8,
        kdaRatio: 1.84,
        kda: "4.4 / 5.3 / 5.4",
        winRate: 60,
        game: 73,
      },
      {
        name: "Gwen",
        cs: 199.4,
        csPerMin: 8,
        kdaRatio: 1.67,
        kda: "5.5 / 5.8 / 4.2",
        winRate: 52,
        game: 60,
      },
      {
        name: "Gnar",
        cs: 192.4,
        csPerMin: 7.8,
        kdaRatio: 1.88,
        kda: "4.9 / 5.4 / 5.2",
        winRate: 51,
        game: 39,
      },
      {
        name: "Akali",
        cs: 176.1,
        csPerMin: 7,
        kdaRatio: 1.7,
        kda: "5.6 / 5.6 / 4.0",
        winRate: 44,
        game: 36,
      },
      {
        name: "Camille",
        cs: 160,
        csPerMin: 6.9,
        kdaRatio: 2.25,
        kda: "5.1 / 4.8 / 5.7",
        winRate: 66,
        game: 29,
      },
      {
        name: "Fiora",
        cs: 187,
        csPerMin: 7.6,
        kdaRatio: 2.19,
        kda: "5.7 / 4.9 / 5.1",
        winRate: 68,
        game: 28,
      },
    ],
  },
  {
    name: "역천괴",
    champs: [
      {
        name: "Karma",
        cs: 26.7,
        csPerMin: 1,
        kdaRatio: 2.63,
        kda: "2.4 / 6.3 / 14.2",
        winRate: 58,
        game: 78,
      },
      {
        name: "Renata Glasc",
        cs: 16.6,
        csPerMin: 0.7,
        kdaRatio: 3.08,
        kda: "1.6 / 5.0 / 13.7",
        winRate: 54,
        game: 67,
      },
      {
        name: "Nautilus",
        cs: 31.9,
        csPerMin: 1.3,
        kdaRatio: 2.37,
        kda: "1.3 / 5.5 / 11.6",
        winRate: 56,
        game: 59,
      },
      {
        name: "Pyke",
        cs: 33.3,
        csPerMin: 1.3,
        kdaRatio: 2.48,
        kda: "5.6 / 6.0 / 9.3",
        winRate: 54,
        game: 46,
      },
      {
        name: "Yuumi",
        cs: 9.8,
        csPerMin: 0.4,
        kdaRatio: 4.94,
        kda: "1.9 / 3.5 / 15.2",
        winRate: 66,
        game: 32,
      },
      {
        name: "Senna",
        cs: 42.1,
        csPerMin: 1.6,
        kdaRatio: 2.61,
        kda: "3.6 / 5.7 / 11.1",
        winRate: 48,
        game: 29,
      },
      {
        name: "Lux",
        cs: 31,
        csPerMin: 1.3,
        kdaRatio: 2.44,
        kda: "3.3 / 5.5 / 10.1",
        winRate: 46,
        game: 28,
      },
    ],
  },
  {
    name: "아 니 맞나",
    champs: [
      {
        name: "Lee Sin",
        cs: 146,
        csPerMin: 5.8,
        kdaRatio: 3.27,
        kda: "7.8 / 5.0 /8.4",
        winRate: 51,
        game: 68,
      },
      {
        name: "Viego",
        cs: 143.2,
        csPerMin: 5.8,
        kdaRatio: 3.08,
        kda: "7.8 / 4.8 / 7.1",
        winRate: 59,
        game: 49,
      },
      {
        name: "Nidalee",
        cs: 158,
        csPerMin: 6.6,
        kdaRatio: 4.12,
        kda: "8.7 / 3.8 / 6.8",
        winRate: 61,
        game: 46,
      },
      {
        name: "Graves",
        cs: 188.1,
        csPerMin: 7.2,
        kdaRatio: 2.29,
        kda: "7.0 / 5.8 / 6.2",
        winRate: 51,
        game: 43,
      },
      {
        name: "Taliyah",
        cs: 188.6,
        csPerMin: 7,
        kdaRatio: 2.82,
        kda: "7.7 / 5.9 / 8.9",
        winRate: 65,
        game: 37,
      },
      {
        name: "Diana",
        cs: 192.6,
        csPerMin: 7,
        kdaRatio: 3.5,
        kda: "8.3 / 5.0 / 9.3",
        winRate: 54,
        game: 28,
      },
      {
        name: "Ekko",
        cs: 176,
        csPerMin: 6.9,
        kdaRatio: 4.28,
        kda: "8.2 / 3.5 / 7.0",
        winRate: 75,
        game: 24,
      },
    ],
  },
  {
    name: "T1 Gumayusi",
    champs: [
      {
        name: "Ezreal",
        cs: 222.4,
        csPerMin: 8.8,
        kdaRatio: 2.21,
        kda: "6.1 / 5.5 / 6.1",
        winRate: 52,
        game: 102,
      },
      {
        name: "Jinx",
        cs: 222.7,
        csPerMin: 9.2,
        kdaRatio: 2.39,
        kda: "6.7 / 5.6 / 6.7",
        winRate: 59,
        game: 66,
      },
      {
        name: "Zeri",
        cs: 214.5,
        csPerMin: 9,
        kdaRatio: 2.66,
        kda: "7.2 / 5.0 / 6.0",
        winRate: 65,
        game: 62,
      },
      {
        name: "Lucian",
        cs: 228.7,
        csPerMin: 8.7,
        kdaRatio: 2.18,
        kda: "8.9 / 7.4 / 7.2",
        winRate: 53,
        game: 53,
      },
      {
        name: "Kalista",
        cs: 205,
        csPerMin: 8.8,
        kdaRatio: 2.37,
        kda: "6.5 / 5.8 / 7.0",
        winRate: 53,
        game: 53,
      },
      {
        name: "Xayah",
        cs: 203.2,
        csPerMin: 8.7,
        kdaRatio: 2.36,
        kda: "6.5 / 5.8 / 7.0",
        winRate: 65,
        game: 48,
      },
      {
        name: "Draven",
        cs: 213.6,
        csPerMin: 8.9,
        kdaRatio: 2.34,
        kda: "7.8 / 5.7 / 5.5",
        winRate: 57,
        game: 47,
      },
    ],
  },
];
